"""Feature registry — metadata for every AI feature on the platform.

Each entry declares the preferred execution layer, provider, model,
token budget, quality requirements, and cost sensitivity for a feature.
The Hybrid Execution Router consults this registry to make routing
decisions without any feature-specific branching in the engine code.
"""
from __future__ import annotations

from dataclasses import dataclass, field

from services.ai.engine.types import ExecutionLayer


@dataclass(frozen=True)
class FeatureMeta:
    feature_id: str
    display_name: str
    preferred_layer: ExecutionLayer
    preferred_provider: str
    preferred_model: str | None
    fallback_layers: tuple[ExecutionLayer, ...]
    max_tokens: int
    priority: str                  # critical | high | medium | low
    requires_reasoning: bool
    cost_sensitivity: str          # high | medium | low
    description: str = ""


_REGISTRY: dict[str, FeatureMeta] = {
    "research_gap_finder": FeatureMeta(
        feature_id="research_gap_finder",
        display_name="Research Gap Finder",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=6000,
        priority="critical",
        requires_reasoning=True,
        cost_sensitivity="low",
        description="Identifies research gaps and novel contribution opportunities",
    ),
    "literature_review": FeatureMeta(
        feature_id="literature_review",
        display_name="Literature Review Assistant",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=6000,
        priority="critical",
        requires_reasoning=True,
        cost_sensitivity="low",
        description="Synthesises literature and generates structured review sections",
    ),
    "manuscript_review": FeatureMeta(
        feature_id="manuscript_review",
        display_name="Manuscript Review",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=6000,
        priority="critical",
        requires_reasoning=True,
        cost_sensitivity="low",
        description="Provides structured peer-review feedback on manuscripts",
    ),
    "statistical_review": FeatureMeta(
        feature_id="statistical_review",
        display_name="Statistical Review",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=6000,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="low",
        description="Reviews statistical methodology and results sections",
    ),
    "research_design_advisor": FeatureMeta(
        feature_id="research_design_advisor",
        display_name="Research Design Advisor",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=3000,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="medium",
        description="Advises on research methodology and study design",
    ),
    "abstract_generator": FeatureMeta(
        feature_id="abstract_generator",
        display_name="Abstract Generator",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=1500,
        priority="high",
        requires_reasoning=False,
        cost_sensitivity="medium",
        description="Generates structured academic abstracts",
    ),
    "ai_rewriting": FeatureMeta(
        feature_id="ai_rewriting",
        display_name="AI Rewriting",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=2000,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="medium",
        description="Rewrites and improves academic text quality",
    ),
    "collaboration_intelligence": FeatureMeta(
        feature_id="collaboration_intelligence",
        display_name="Collaboration Intelligence",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=6000,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="low",
        description="Analyses collaboration potential and research synergies",
    ),
    "ai_assistant": FeatureMeta(
        feature_id="ai_assistant",
        display_name="AI Research Assistant",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=2048,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="medium",
        description="General-purpose academic research assistant",
    ),
    "ai_chat": FeatureMeta(
        feature_id="ai_chat",
        display_name="Synaptiq AI OS Chat",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=3000,
        priority="critical",
        requires_reasoning=True,
        cost_sensitivity="medium",
        description="Multi-turn AI assistant with specialist domain agents",
    ),
    "journal_matching": FeatureMeta(
        feature_id="journal_matching",
        display_name="Journal Matching",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=2048,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="medium",
        description="Ranks journals by manuscript fit using AI scoring",
    ),
    "conference_matching": FeatureMeta(
        feature_id="conference_matching",
        display_name="Conference Matching",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=2048,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="medium",
        description="Ranks conferences by fit for a manuscript submission",
    ),
    "grant_matching": FeatureMeta(
        feature_id="grant_matching",
        display_name="Grant Matching",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=2048,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="medium",
        description="Matches researchers to relevant funding opportunities",
    ),
    "reviewer_matching": FeatureMeta(
        feature_id="reviewer_matching",
        display_name="Reviewer Matching",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=2048,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="medium",
        description="Recommends qualified, unbiased peer reviewers",
    ),
    "teaching_lesson_generation": FeatureMeta(
        feature_id="teaching_lesson_generation",
        display_name="Teaching — Lesson Generation",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=4000,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="medium",
        description="Generates structured lesson plans and teaching materials",
    ),
    "teaching_assessment_generation": FeatureMeta(
        feature_id="teaching_assessment_generation",
        display_name="Teaching — Assessment Generation",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=6000,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="medium",
        description="Creates assessments, rubrics, and grading criteria",
    ),
    "teaching_assistant": FeatureMeta(
        feature_id="teaching_assistant",
        display_name="Teaching AI Assistant",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=1500,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="medium",
        description="Conversational teaching support assistant",
    ),
    "grant_gap_detection": FeatureMeta(
        feature_id="grant_gap_detection",
        display_name="Grant Gap Detection",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=2048,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="medium",
        description="Identifies gaps in grant applications and suggests improvements",
    ),
    "marketplace_matching": FeatureMeta(
        feature_id="marketplace_matching",
        display_name="Reviewer Marketplace Matching",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=2048,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="medium",
        description="Matches manuscripts to expert marketplace reviewers",
    ),
    "admin_copilot": FeatureMeta(
        feature_id="admin_copilot",
        display_name="Admin AI Copilot",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-haiku-4-5-20251001",
        fallback_layers=(ExecutionLayer.RULE,),
        max_tokens=1024,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Generates executive briefings and answers admin platform queries",
    ),
    "recommendation_engine": FeatureMeta(
        feature_id="recommendation_engine",
        display_name="Recommendation Engine",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model="claude-sonnet-4-6",
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=2048,
        priority="high",
        requires_reasoning=True,
        cost_sensitivity="medium",
        description="Generates personalised collaboration and research recommendations",
    ),
    # ── Rule Engine native features (zero LLM cost) ────────────────────────
    "profile_completion": FeatureMeta(
        feature_id="profile_completion",
        display_name="Profile Completion Score",
        preferred_layer=ExecutionLayer.RULE,
        preferred_provider="rule_engine",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=0,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Deterministic profile completeness scoring — zero AI cost",
    ),
    "keyword_extraction": FeatureMeta(
        feature_id="keyword_extraction",
        display_name="Keyword Extraction",
        preferred_layer=ExecutionLayer.RULE,
        preferred_provider="rule_engine",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=0,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="TF-based keyword extraction — zero AI cost",
    ),
    "reference_validation": FeatureMeta(
        feature_id="reference_validation",
        display_name="Reference Validation",
        preferred_layer=ExecutionLayer.RULE,
        preferred_provider="rule_engine",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=0,
        priority="high",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Deterministic APA/IEEE reference validation — zero AI cost",
    ),
    "alert_generation": FeatureMeta(
        feature_id="alert_generation",
        display_name="Alert Generation",
        preferred_layer=ExecutionLayer.RULE,
        preferred_provider="rule_engine",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=0,
        priority="high",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Threshold-based alert generation — zero AI cost",
    ),
    "citation_metrics": FeatureMeta(
        feature_id="citation_metrics",
        display_name="Citation Metrics",
        preferred_layer=ExecutionLayer.RULE,
        preferred_provider="rule_engine",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=0,
        priority="high",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="H-index, G-index, I10, citation summary — zero AI cost",
    ),
    "research_stats": FeatureMeta(
        feature_id="research_stats",
        display_name="Research Statistics",
        preferred_layer=ExecutionLayer.RULE,
        preferred_provider="rule_engine",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=0,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Statistical analysis (mean, trend, forecast, etc.) — zero AI cost",
    ),
    "profile_report": FeatureMeta(
        feature_id="profile_report",
        display_name="Profile Report",
        preferred_layer=ExecutionLayer.RULE,
        preferred_provider="rule_engine",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=0,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Template-based profile quality report — zero AI cost",
    ),
    "general": FeatureMeta(
        feature_id="general",
        display_name="General AI",
        preferred_layer=ExecutionLayer.CLOUD,
        preferred_provider="anthropic",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.LOCAL, ExecutionLayer.RULE),
        max_tokens=2048,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="medium",
        description="Fallback for unclassified AI requests",
    ),
    # ── Local AI native features (zero cloud cost when local is available) ──
    "summarization": FeatureMeta(
        feature_id="summarization",
        display_name="Summarization",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=1024,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Document, section, or paragraph summarization",
    ),
    "grammar_correction": FeatureMeta(
        feature_id="grammar_correction",
        display_name="Grammar Correction",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=2048,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Grammar and spelling correction for academic text",
    ),
    "academic_proofreading": FeatureMeta(
        feature_id="academic_proofreading",
        display_name="Academic Proofreading",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=2048,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Academic proofreading and style correction",
    ),
    "paraphrasing": FeatureMeta(
        feature_id="paraphrasing",
        display_name="Paraphrasing",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=2048,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Academic paraphrasing of text sections",
    ),
    "translation": FeatureMeta(
        feature_id="translation",
        display_name="Translation",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=2048,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Academic text translation to target language",
    ),
    "title_generation": FeatureMeta(
        feature_id="title_generation",
        display_name="Title Generation",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=256,
        priority="low",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Academic paper title generation",
    ),
    "subtitle_generation": FeatureMeta(
        feature_id="subtitle_generation",
        display_name="Subtitle Generation",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=256,
        priority="low",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Paper subtitle and section heading generation",
    ),
    "outline_generation": FeatureMeta(
        feature_id="outline_generation",
        display_name="Outline Generation",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=1024,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Research paper outline and structure generation",
    ),
    "bullet_points": FeatureMeta(
        feature_id="bullet_points",
        display_name="Bullet Points",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=512,
        priority="low",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Convert text to structured bullet points",
    ),
    "plain_language_explanation": FeatureMeta(
        feature_id="plain_language_explanation",
        display_name="Plain Language Explanation",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=1024,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Explain academic content in plain, accessible language",
    ),
    "research_brainstorming": FeatureMeta(
        feature_id="research_brainstorming",
        display_name="Research Brainstorming",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=1024,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Brainstorm research directions and ideas",
    ),
    "writing_improvement": FeatureMeta(
        feature_id="writing_improvement",
        display_name="Writing Improvement",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=2048,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Improve clarity and quality of academic writing",
    ),
    "academic_tone": FeatureMeta(
        feature_id="academic_tone",
        display_name="Academic Tone Adjustment",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=2048,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Adjust text to formal academic tone",
    ),
    "email_drafting": FeatureMeta(
        feature_id="email_drafting",
        display_name="Email Drafting",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=512,
        priority="low",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Draft professional academic emails",
    ),
    "teaching_simplification": FeatureMeta(
        feature_id="teaching_simplification",
        display_name="Teaching — Simplification",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=1024,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Simplify teaching material for student comprehension",
    ),
    "teaching_explanation": FeatureMeta(
        feature_id="teaching_explanation",
        display_name="Teaching — Explanation",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=1024,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Generate teaching explanations for concepts",
    ),
    "local_chat": FeatureMeta(
        feature_id="local_chat",
        display_name="Synaptiq AI — Local Chat",
        preferred_layer=ExecutionLayer.LOCAL,
        preferred_provider="local",
        preferred_model=None,
        fallback_layers=(ExecutionLayer.CLOUD,),
        max_tokens=1024,
        priority="medium",
        requires_reasoning=False,
        cost_sensitivity="high",
        description="Simple conversational AI interactions via local model",
    ),
}


def get_feature_meta(feature_id: str) -> FeatureMeta:
    """Return feature metadata; falls back to 'general' for unknown feature IDs."""
    return _REGISTRY.get(feature_id) or _REGISTRY["general"]


def list_features() -> list[FeatureMeta]:
    return list(_REGISTRY.values())


def get_all_feature_ids() -> list[str]:
    return list(_REGISTRY.keys())
