"""SDK generation — Phase XXXV.7.

Generates Python and TypeScript client stubs from the live OpenAPI schema.
The generated code is functional boilerplate; it is NOT a full SDK library.
"""
from __future__ import annotations

import json
import re
from typing import Any


def _snake(name: str) -> str:
    """Convert CamelCase or kebab-case to snake_case."""
    name = re.sub(r"[-/]", "_", name)
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    name = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", name)
    return name.lower().strip("_")


def _camel(name: str) -> str:
    parts = re.split(r"[_\-\s]", name)
    return parts[0] + "".join(p.title() for p in parts[1:])


def generate_python_sdk(openapi_spec: dict) -> str:
    """Return a Python SDK module as a string."""
    title   = openapi_spec.get("info", {}).get("title", "Synaptiq")
    version = openapi_spec.get("info", {}).get("version", "1.0")
    paths   = openapi_spec.get("paths", {})

    methods: list[str] = []
    for path, path_item in paths.items():
        for method, op in path_item.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue
            op_id   = op.get("operationId") or _snake(f"{method}_{path}")
            fn_name = _snake(op_id)
            summary = op.get("summary", "")
            has_body = method in ("post", "put", "patch")
            body_arg = ", body: dict | None = None" if has_body else ""
            body_kw  = ", json=body" if has_body else ""

            methods.append(f"""
    def {fn_name}(self, **params{body_arg}) -> dict:
        \"\"\"{summary}\"\"\"
        return self._request("{method.upper()}", "{path}"{body_kw}, params=params)
""")

    lines = f'''"""
Auto-generated Python SDK for {title} (v{version})
Generated by Synaptiq API Platform — Phase XXXV.7
"""
from __future__ import annotations

import json
import urllib.request
import urllib.parse
from typing import Any


class SynaptiqClient:
    """Minimal Python client for the Synaptiq API."""

    def __init__(self, base_url: str = "https://api.synaptiq.academy", api_key: str = "") -> None:
        self.base_url = base_url.rstrip("/")
        self.api_key  = api_key

    def _request(self, method: str, path: str, json: Any = None, params: dict | None = None) -> dict:
        url = self.base_url + path
        if params:
            clean = {{k: v for k, v in params.items() if v is not None}}
            if clean:
                url += "?" + urllib.parse.urlencode(clean)
        headers = {{
            "Content-Type":  "application/json",
            "Authorization": f"Bearer {{self.api_key}}",
        }}
        data = json.dumps(json).encode() if json else None
        req  = urllib.request.Request(url, data=data, headers=headers, method=method)
        with urllib.request.urlopen(req) as resp:
            return globals()["json"].loads(resp.read())
{"".join(methods)}

def create_client(base_url: str, api_key: str) -> SynaptiqClient:
    return SynaptiqClient(base_url=base_url, api_key=api_key)
'''
    return lines


def generate_typescript_sdk(openapi_spec: dict) -> str:
    """Return a TypeScript SDK module as a string."""
    title   = openapi_spec.get("info", {}).get("title", "Synaptiq")
    version = openapi_spec.get("info", {}).get("version", "1.0")
    paths   = openapi_spec.get("paths", {})

    methods: list[str] = []
    for path, path_item in paths.items():
        for method, op in path_item.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue
            op_id   = op.get("operationId") or _camel(f"{method}_{path}")
            fn_name = _camel(op_id)
            summary = op.get("summary", "")
            has_body = method in ("post", "put", "patch")
            body_arg = ", body?: Record<string, unknown>" if has_body else ""
            body_kw  = ", body" if has_body else ""

            methods.append(f"""
  /** {summary} */
  async {fn_name}(params?: Record<string, unknown>{body_arg}): Promise<unknown> {{
    return this.request("{method.upper()}", "{path}", params{body_kw});
  }}""")

    lines = f'''/**
 * Auto-generated TypeScript SDK for {title} (v{version})
 * Generated by Synaptiq API Platform — Phase XXXV.7
 */

export interface SynaptiqConfig {{
  baseUrl?: string;
  apiKey:   string;
}}

export class SynaptiqClient {{
  private baseUrl: string;
  private apiKey:  string;

  constructor(config: SynaptiqConfig) {{
    this.baseUrl = (config.baseUrl ?? "https://api.synaptiq.academy").replace(/\\/$/, "");
    this.apiKey  = config.apiKey;
  }}

  private async request(
    method: string,
    path:   string,
    params?: Record<string, unknown>,
    body?:   Record<string, unknown>,
  ): Promise<unknown> {{
    let url = this.baseUrl + path;
    if (params) {{
      const qs = new URLSearchParams(
        Object.entries(params).filter(([, v]) => v != null).map(([k, v]) => [k, String(v)])
      ).toString();
      if (qs) url += "?" + qs;
    }}
    const res = await fetch(url, {{
      method,
      headers: {{
        "Content-Type":  "application/json",
        "Authorization": `Bearer ${{this.apiKey}}`,
      }},
      ...(body ? {{ body: JSON.stringify(body) }} : {{}}),
    }});
    return res.json();
  }}
{"".join(methods)}
}}

export function createClient(config: SynaptiqConfig): SynaptiqClient {{
  return new SynaptiqClient(config);
}}
'''
    return lines
