// Centralized data-testid registry (kebab-case, role-based)
export const TID = {
  // Landing
  landingGetStarted: "landing-get-started-btn",
  landingLoginLink: "landing-login-link",
  landingHero: "landing-hero",
  // Auth
  loginEmail: "login-email-input",
  loginPassword: "login-password-input",
  loginSubmit: "login-submit-btn",
  loginError: "login-error",
  loginForgotLink: "login-forgot-link",
  registerName: "register-name-input",
  registerEmail: "register-email-input",
  registerPassword: "register-password-input",
  registerSubmit: "register-submit-btn",
  registerError: "register-error",
  authToggleLink: "auth-toggle-link",
  forgotEmail: "forgot-email-input",
  forgotSubmit: "forgot-submit-btn",
  forgotSent: "forgot-sent",
  resetNewPassword: "reset-new-password-input",
  resetConfirmPassword: "reset-confirm-password-input",
  resetSubmit: "reset-submit-btn",
  resetError: "reset-error",
  // Onboarding (multi-step)
  onboardingForm: "onboarding-form",
  onboardingSubmit: "onboarding-submit-btn",
  onboardingSkip: "onboarding-skip-btn",
  onbNext: "onb-next-btn",
  onbError: "onb-error",
  onbFirstName: "onb-first-name",
  onbLastName: "onb-last-name",
  onbCountry: "onb-country",
  onbRole: "onb-role",
  onbInstitution: "onb-institution",
  onbDepartment: "onb-department",
  onbAreaChip: "onb-area",
  onbInterests: "onb-interests",
  onbKeywords: "onb-keywords",
  onbOrcid: "onb-orcid",
  onbScholar: "onb-scholar",
  onbRgate: "onb-researchgate",
  onbLinkedin: "onb-linkedin",
  onbPubs: "onb-publications",
  onbConfs: "onb-conferences",
  // Shell
  sidebar: "app-sidebar",
  navDiscover: "nav-discover",
  navCollaborations: "nav-collaborations",
  navNetwork: "nav-network",
  navProjects: "nav-projects",
  navMessages: "nav-messages",
  navAnalytics: "nav-analytics",
  navNotifications: "nav-notifications",
  navSettings: "nav-settings",
  navProfile: "nav-profile",
  navDiscoverToggle: "nav-discover-toggle",
  navProjectsToggle: "nav-projects-toggle",
  navJournals: "nav-journals",
  navConferences: "nav-conferences",
  navFunding: "nav-funding",
  navGrants: "nav-grants",
  navPublicationHub: "nav-publication-hub",
  navRepository: "nav-repository",
  navWorkspaces: "nav-workspaces",
  navManuscripts: "nav-manuscripts",
  creditsWidget: "credits-widget",
  logoutBtn: "logout-btn",
  // Discover
  discoverFeed: "discover-feed",
  discoverCollabCard: (id) => `discover-collab-${id}`,
  discoverResearcherCard: (id) => `discover-researcher-${id}`,
  aiRecommendBtn: "ai-recommend-btn",
  aiRecommendList: "ai-recommend-list",
  // Collaborations
  collabList: "collab-list",
  collabCard: (id) => `collab-card-${id}`,
  collabSearch: "collab-search-input",
  collabCreateBtn: "collab-create-btn",
  collabApplyBtn: "collab-apply-btn",
  collabApplyMessage: "collab-apply-message",
  collabApplySubmit: "collab-apply-submit",
  collabCreateTitle: "collab-create-title",
  collabCreateDescription: "collab-create-description",
  collabCreateType: "collab-create-type",
  collabCreateArea: "collab-create-area",
  collabCreateSubmit: "collab-create-submit",
  // Network
  networkSearch: "network-search-input",
  networkList: "network-list",
  // Profile
  profileEditBtn: "profile-edit-btn",
  profileMessageBtn: "profile-message-btn",
  profileConnectBtn: "profile-connect-btn",
  // Projects
  projectList: "project-list",
  projectCreateBtn: "project-create-btn",
  projectCard: (id) => `project-card-${id}`,
  // Messages
  messageInput: "message-input",
  messageSendBtn: "message-send-btn",
  messageList: "message-list",
  conversationItem: (id) => `conversation-${id}`,
  convList: "conv-list",
  convSearch: "conv-search-input",
  convItem: (id) => `conv-${id}`,
  convFilter: (kind) => `conv-filter-${kind}`,
  convUnread: (id) => `conv-unread-${id}`,
  attachBtn: "msg-attach-btn",
  shareBtn: "msg-share-btn",
  shareTab: (kind) => `share-tab-${kind}`,
  typingIndicator: "typing-indicator",
  openChatBtn: "open-chat-btn",
  // Analytics
  analyticsDashboard: "analytics-dashboard",
  // Notifications
  notificationsList: "notifications-list",
  // Journals
  journalsSearch: "journals-search-input",
  journalsList: "journals-list",
  journalCard: (id) => `journal-card-${id}`,
  // Conferences
  conferencesSearch: "conferences-search-input",
  conferencesList: "conferences-list",
  conferenceCard: (id) => `conference-card-${id}`,
  // Funding
  fundingSearch: "funding-search-input",
  fundingList: "funding-list",
  fundingCard: (id) => `funding-card-${id}`,
  fundingSaveBtn: "funding-save-btn",
  // Grants
  grantsList: "grants-list",
  grantsTab: (key) => `grants-tab-${key}`,
  // Workspaces
  workspaceList: "workspace-list",
  workspaceCreateBtn: "workspace-create-btn",
  workspaceNewName: "workspace-new-name",
  workspaceNewSubmit: "workspace-new-submit",
  workspaceCard: (id) => `workspace-card-${id}`,
  workspaceNoteInput: "workspace-note-input",
  workspaceNoteSubmit: "workspace-note-submit",
  workspaceInviteBtn: "workspace-invite-btn",
  workspaceInviteSubmit: "workspace-invite-submit",
  workspaceInviteUserPick: (id) => `workspace-invite-user-${id}`,
  workspaceInviteRole: "workspace-invite-role",
  workspaceMemberRole: (uid) => `workspace-member-role-${uid}`,
  workspaceMemberRemove: (uid) => `workspace-member-remove-${uid}`,
  workspaceInvitationAccept: (id) => `workspace-inv-accept-${id}`,
  workspaceInvitationDecline: (id) => `workspace-inv-decline-${id}`,
  workspaceTab: (key) => `workspace-tab-${key}`,
  workspaceHealth: "workspace-health",
  workspaceUpcomingMilestones: "workspace-upcoming-milestones",
  workspaceLinkedManuscripts: "workspace-linked-manuscripts",
  workspaceYourRole: "workspace-your-role",
  workspaceInviteSearch: "workspace-invite-search",
  // Manuscripts
  manuscriptList: "manuscript-list",
  manuscriptCreateBtn: "manuscript-create-btn",
  manuscriptNewTitle: "manuscript-new-title",
  manuscriptNewSubmit: "manuscript-new-submit",
  manuscriptCard: (id) => `manuscript-card-${id}`,
  manuscriptSection: (key) => `manuscript-section-${key}`,
  manuscriptStatus: "manuscript-status-select",
  manuscriptSaveBtn: "manuscript-save-btn",
  manuscriptEditor: "manuscript-editor",
  manuscriptSnapshotBtn: "manuscript-snapshot-btn",
  manuscriptVersionsToggle: "manuscript-versions-toggle",
  manuscriptVersionItem: (v) => `manuscript-version-${v}`,
  manuscriptVersionRestore: (v) => `manuscript-version-restore-${v}`,
  manuscriptCommentBody: "manuscript-comment-body",
  manuscriptCommentSubmit: "manuscript-comment-submit",
  manuscriptCommentItem: (id) => `manuscript-comment-${id}`,
  manuscriptCommentResolve: (id) => `manuscript-comment-resolve-${id}`,
  manuscriptAuthorUp: (uid) => `manuscript-author-up-${uid}`,
  manuscriptAuthorDown: (uid) => `manuscript-author-down-${uid}`,
  manuscriptCorrespondingPick: (uid) => `manuscript-corr-pick-${uid}`,
  manuscriptReadiness: "manuscript-readiness",
  // Kanban (workspace tasks)
  kanban: "workspace-kanban",
  kanbanColumn: (status) => `kanban-col-${status}`,
  kanbanTask: (id) => `kanban-task-${id}`,
  kanbanAddBtn: (status) => `kanban-add-${status}`,
  kanbanNewTitle: (status) => `kanban-new-title-${status}`,
  kanbanNewSubmit: (status) => `kanban-new-submit-${status}`,
  kanbanProjectPicker: "kanban-project-picker",
  // Manuscript review workflow
  manuscriptReviewsTab: "manuscript-reviews-tab",
  manuscriptReviewAssignBtn: "manuscript-review-assign-btn",
  manuscriptReviewAssignSubmit: "manuscript-review-assign-submit",
  manuscriptReviewPick: (uid) => `manuscript-review-pick-${uid}`,
  manuscriptReviewItem: (id) => `manuscript-review-${id}`,
  // Reviewer dashboard
  reviewsDashboard: "reviews-dashboard",
  reviewItem: (id) => `review-item-${id}`,
  reviewAcceptBtn: (id) => `review-accept-${id}`,
  reviewDeclineBtn: (id) => `review-decline-${id}`,
  reviewVerdictBtn: (id) => `review-verdict-${id}`,
  reviewVerdictSelect: (id) => `review-verdict-select-${id}`,
  reviewVerdictSubmit: (id) => `review-verdict-submit-${id}`,
  reviewVerdictComment: (id) => `review-verdict-comment-${id}`,
  navReviews: "nav-reviews",
  navAIManuscriptReview: "nav-ai-manuscript-review",
  navLiteratureReview: "nav-literature-review",
  navResearchImpact: "nav-research-impact",
  navAIUsage: "nav-ai-usage",
  // AI Manuscript Review
  manuscriptReviewAnalyzeBtn: "manuscript-review-analyze-btn",
  manuscriptReviewResult: "manuscript-review-result",
  manuscriptReviewHistoryItem: (id) => `manuscript-review-history-${id}`,
  // AI Literature Review
  literatureReviewForm: "literature-review-form",
  literatureReviewTopic: "literature-review-topic",
  literatureReviewQuestion: "literature-review-question",
  literatureReviewKeywords: "literature-review-keywords",
  literatureReviewSubmitBtn: "literature-review-submit-btn",
  literatureReviewResult: "literature-review-result",
  literatureReviewHistoryItem: (id) => `literature-review-history-${id}`,
  // Citation Monitoring (legacy dashboard)
  navCitationMonitoring: "nav-citation-monitoring",
  citationMonitoringDashboard: "citation-monitoring-dashboard",
  citationMonitoringSyncBtn: "citation-monitoring-sync-btn",
  citationMonitoringExportBtn: "citation-monitoring-export-btn",
  citationMonitoringPubRow: (id) => `citation-pub-row-${id}`,
  // Citation Tracker (new)
  navCitations: "nav-citations",
  citationsDashboard: "citations-dashboard",
  citationsSyncBtn: "citations-sync-btn",
  citationsExportBtn: "citations-export-btn",
  citationsImportBtn: "citations-import-btn",
  citationPubRow: (id) => `citation-pub-row-${id}`,
  citationDetailPage: (id) => `citation-detail-${id}`,
  // AI Statistical Review
  navStatisticalReview: "nav-statistical-review",
  statisticalReviewForm: "statistical-review-form",
  statisticalReviewTopic: "statistical-review-topic",
  statisticalReviewQuestion: "statistical-review-question",
  statisticalReviewResults: "statistical-review-results",
  statisticalReviewSubmitBtn: "statistical-review-submit-btn",
  statisticalReviewResult: "statistical-review-result",
  statisticalReviewHistoryItem: (id) => `statistical-review-history-${id}`,
  // AI Research Design Advisor
  navResearchDesignAdvisor: "nav-research-design-advisor",
  researchDesignForm: "research-design-form",
  researchDesignTopic: "research-design-topic",
  researchDesignQuestion: "research-design-question",
  researchDesignObjective: "research-design-objective",
  researchDesignSubmitBtn: "research-design-submit-btn",
  researchDesignResult: "research-design-result",
  researchDesignHistoryItem: (id) => `research-design-history-${id}`,
  // AI Research Gap Finder
  navResearchGapFinder: "nav-research-gap-finder",
  researchGapForm: "research-gap-form",
  researchGapTopic: "research-gap-topic",
  researchGapQuestion: "research-gap-question",
  researchGapKeywords: "research-gap-keywords",
  researchGapSubmitBtn: "research-gap-submit-btn",
  researchGapResult: "research-gap-result",
  researchGapHistoryItem: (id) => `research-gap-history-${id}`,
  // Collaboration Intelligence
  navCollaborationIntelligence: "nav-collaboration-intelligence",
  navCollabRequests: "nav-collab-requests",
  collabRequestsDashboard: "collab-requests-dashboard",
  collabRequestCard: (id) => `collab-request-card-${id}`,
  collaborationIntelDashboard: "collaboration-intel-dashboard",
  collaborationIntelGenerateBtn: "collaboration-intel-generate-btn",
  collaborationIntelResults: "collaboration-intel-results",
  collaborationIntelHistoryItem: (id) => `collaboration-intel-history-${id}`,
  collaborationIntelResearcherCard: (id) => `collaboration-intel-card-${id}`,
  navMarketplace: "nav-marketplace",
  navExpertise: "nav-expertise",
  navInstitutions: "nav-institutions",
  navDepartments:  "nav-departments",
  // Department Management
  departmentsPage:           "departments-page",
  deptGrid:                  "dept-grid",
  deptEmpty:                 "dept-empty",
  deptSearch:                "dept-search",
  deptCreateBtn:             "dept-create-btn",
  deptCreateModal:           "dept-create-modal",
  deptNameInput:             "dept-name-input",
  deptCreateSubmit:          "dept-create-submit",
  deptCard:                  (id) => `dept-card-${id}`,
  deptDetailPage:            (id) => `dept-detail-${id}`,
  deptName:                  "dept-name",
  deptTabs:                  "dept-tabs",
  deptTab:                   (t) => `dept-tab-${t}`,
  deptEditBtn:               "dept-edit-btn",
  deptEditModal:             "dept-edit-modal",
  deptEditSubmit:            "dept-edit-submit",
  deptManageMembersBtn:      "dept-manage-members-btn",
  deptManageMembersModal:    "dept-manage-members-modal",
  deptPickMember:            (uid) => `dept-pick-member-${uid}`,
  deptSaveMembersBtn:        "dept-save-members-btn",
  deptFacultyList:           "dept-faculty-list",
  deptFacultyCard:           (uid) => `dept-faculty-card-${uid}`,
  deptProjectsList:          "dept-projects-list",
  deptProjectCard:           (id) => `dept-project-card-${id}`,
  deptLinkProjectBtn:        "dept-link-project-btn",
  deptLinkProjectInput:      "dept-link-project-input",
  deptUnlinkProjectBtn:      (id) => `dept-unlink-project-${id}`,
  deptPublicationsList:      "dept-publications-list",
  deptPublicationRow:        (id) => `dept-publication-row-${id}`,
  deptGrantsList:            "dept-grants-list",
  deptGrantRow:              (id) => `dept-grant-row-${id}`,
  deptStatisticsTable:       "dept-statistics-table",
  deptRankingsTable:         "dept-rankings-table",
  deptRankingRow:            (id) => `dept-ranking-row-${id}`,
  deptNetworkList:           "dept-network-list",
  // Discovery Suite
  discoverySearch: "discovery-search",
  discoveryFacet: (k, v) => `discovery-facet-${k}-${v}`,
  discoverySortSelect: "discovery-sort",
  discoveryPageNext: "discovery-page-next",
  discoveryPagePrev: "discovery-page-prev",
  discoveryItem: (id) => `discovery-item-${id}`,
  discoveryTabConferences: "discovery-tab-conferences",
  discoveryTabJournals: "discovery-tab-journals",
  discoveryTabGrants: "discovery-tab-grants",
  // Publication hub
  pubhubStageColumn: (s) => `pubhub-col-${s}`,
  pubhubManuscript: (mid) => `pubhub-manuscript-${mid}`,
  pubhubSubmissionCard: (sid) => `pubhub-sub-${sid}`,
  pubhubSelectVenueBtn: (mid) => `pubhub-select-venue-${mid}`,
  pubhubSubmitBtn: (mid) => `pubhub-submit-${mid}`,
  // Publication Hub
  publicationHub: "publication-hub",
  publicationPipeline: "publication-pipeline",
  // Repository
  repository: "repository",
  repositorySearch: "repository-search-input",
  repositoryCreateBtn: "repository-create-btn",
  repositoryNewTitle: "repository-new-title",
  repositoryNewSubmit: "repository-new-submit",
  // Pricing
  pricingHero: "pricing-hero",
  pricingPlans: "pricing-plans",
  pricingPlanCard: (code) => `pricing-plan-${code}`,
  pricingChooseBtn: (code) => `pricing-choose-${code}`,
  pricingBillMonthly: "pricing-bill-monthly",
  pricingBillAnnual: "pricing-bill-annual",
  // Contact
  contactForm: "contact-form",
  contactName: "contact-name",
  contactEmail: "contact-email",
  contactMessage: "contact-message",
  contactSubmit: "contact-submit",
  // Research Impact Dashboard
  researchImpactPage:    "research-impact-page",
  impactKPIs:            "impact-kpis",
  impactPubSpotlight:    "impact-pub-spotlight",
  impactCitationChart:   "impact-citation-chart",
  impactResearchAreas:   "impact-research-areas",
  impactCollabs:         "impact-collabs",
  impactProjects:        "impact-projects",
  impactOpportunities:   "impact-opportunities",
  impactScorecard:       "impact-scorecard",
  impactInsights:        "impact-insights",
  impactGoals:           "impact-goals",
  impactExport:          "impact-export",
  // Settings
  settingsCurrentPassword: "settings-current-password",
  settingsNewPassword: "settings-new-password",
  settingsConfirmPassword: "settings-confirm-password",
  settingsChangePasswordSubmit: "settings-change-password-submit",
  settingsSeePlans: "settings-see-plans",
};
