"""Feature execution profiles — routing intelligence for all 46 Synaptiq features.

Each profile extends the existing FeatureMeta with routing-specific data:
  base_complexity, priority_score, cacheable, min_subscription_tier,
  allow_local_downgrade, allow_rule_downgrade.
"""
from __future__ import annotations

from dataclasses import dataclass

from services.smart_router.types import ComplexityLevel


@dataclass(frozen=True)
class FeatureProfile:
    feature_id: str
    base_complexity: ComplexityLevel
    priority_score: int              # 1 = highest, 100 = lowest
    cacheable: bool                  # can output be cached for identical inputs?
    min_subscription_tier: str       # free | pro | institution
    allow_local_downgrade: bool      # can route to LOCAL if budget tight?
    allow_rule_downgrade: bool       # can route to RULE if LOCAL unavailable?
    typical_context_tokens: int      # typical combined context size
    expected_output_tokens: int      # expected output size


# Priority scores map to request priority in queue:
#   1–15  = CRITICAL (institution + research core)
#   16–30 = HIGH (research tools)
#   31–50 = MEDIUM (writing aids)
#   51–80 = LOW (local tasks)
#   81–100 = VERY_LOW (rule-based)

_PROFILES: dict[str, FeatureProfile] = {
    # ── CRITICAL / CLOUD-only ───────────────────────────────────────────────
    "ai_chat": FeatureProfile(
        feature_id="ai_chat",
        base_complexity=ComplexityLevel.CRITICAL,
        priority_score=5,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=4000,
        expected_output_tokens=1200,
    ),
    "research_gap_finder": FeatureProfile(
        feature_id="research_gap_finder",
        base_complexity=ComplexityLevel.CRITICAL,
        priority_score=8,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=False,
        allow_rule_downgrade=False,
        typical_context_tokens=5000,
        expected_output_tokens=3000,
    ),
    "literature_review": FeatureProfile(
        feature_id="literature_review",
        base_complexity=ComplexityLevel.CRITICAL,
        priority_score=9,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=False,
        allow_rule_downgrade=False,
        typical_context_tokens=6000,
        expected_output_tokens=3500,
    ),
    "manuscript_review": FeatureProfile(
        feature_id="manuscript_review",
        base_complexity=ComplexityLevel.CRITICAL,
        priority_score=10,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=False,
        allow_rule_downgrade=False,
        typical_context_tokens=6000,
        expected_output_tokens=2500,
    ),
    "collaboration_intelligence": FeatureProfile(
        feature_id="collaboration_intelligence",
        base_complexity=ComplexityLevel.CRITICAL,
        priority_score=12,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=False,
        allow_rule_downgrade=False,
        typical_context_tokens=4000,
        expected_output_tokens=2500,
    ),
    # ── HIGH ────────────────────────────────────────────────────────────────
    "statistical_review": FeatureProfile(
        feature_id="statistical_review",
        base_complexity=ComplexityLevel.HIGH,
        priority_score=16,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=False,
        allow_rule_downgrade=False,
        typical_context_tokens=4000,
        expected_output_tokens=2000,
    ),
    "research_design_advisor": FeatureProfile(
        feature_id="research_design_advisor",
        base_complexity=ComplexityLevel.HIGH,
        priority_score=18,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=2000,
        expected_output_tokens=1500,
    ),
    "ai_assistant": FeatureProfile(
        feature_id="ai_assistant",
        base_complexity=ComplexityLevel.HIGH,
        priority_score=15,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=3000,
        expected_output_tokens=1000,
    ),
    "teaching_assessment_generation": FeatureProfile(
        feature_id="teaching_assessment_generation",
        base_complexity=ComplexityLevel.HIGH,
        priority_score=20,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=3000,
        expected_output_tokens=1500,
    ),
    "teaching_lesson_generation": FeatureProfile(
        feature_id="teaching_lesson_generation",
        base_complexity=ComplexityLevel.HIGH,
        priority_score=22,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=2000,
        expected_output_tokens=2000,
    ),
    "grant_matching": FeatureProfile(
        feature_id="grant_matching",
        base_complexity=ComplexityLevel.HIGH,
        priority_score=17,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=True,
        allow_rule_downgrade=True,
        typical_context_tokens=2000,
        expected_output_tokens=800,
    ),
    "grant_gap_detection": FeatureProfile(
        feature_id="grant_gap_detection",
        base_complexity=ComplexityLevel.HIGH,
        priority_score=19,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=3000,
        expected_output_tokens=1200,
    ),
    "journal_matching": FeatureProfile(
        feature_id="journal_matching",
        base_complexity=ComplexityLevel.HIGH,
        priority_score=24,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=True,
        allow_rule_downgrade=True,
        typical_context_tokens=2000,
        expected_output_tokens=800,
    ),
    "conference_matching": FeatureProfile(
        feature_id="conference_matching",
        base_complexity=ComplexityLevel.HIGH,
        priority_score=25,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=True,
        allow_rule_downgrade=True,
        typical_context_tokens=2000,
        expected_output_tokens=800,
    ),
    "reviewer_matching": FeatureProfile(
        feature_id="reviewer_matching",
        base_complexity=ComplexityLevel.HIGH,
        priority_score=26,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=True,
        allow_rule_downgrade=True,
        typical_context_tokens=2000,
        expected_output_tokens=800,
    ),
    "marketplace_matching": FeatureProfile(
        feature_id="marketplace_matching",
        base_complexity=ComplexityLevel.HIGH,
        priority_score=27,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=True,
        allow_rule_downgrade=True,
        typical_context_tokens=2000,
        expected_output_tokens=800,
    ),
    "recommendation_engine": FeatureProfile(
        feature_id="recommendation_engine",
        base_complexity=ComplexityLevel.HIGH,
        priority_score=28,
        cacheable=True,
        min_subscription_tier="pro",
        allow_local_downgrade=True,
        allow_rule_downgrade=True,
        typical_context_tokens=2000,
        expected_output_tokens=1000,
    ),
    # ── MEDIUM ───────────────────────────────────────────────────────────────
    "abstract_generator": FeatureProfile(
        feature_id="abstract_generator",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=32,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=2000,
        expected_output_tokens=600,
    ),
    "ai_rewriting": FeatureProfile(
        feature_id="ai_rewriting",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=35,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=1500,
        expected_output_tokens=800,
    ),
    "teaching_assistant": FeatureProfile(
        feature_id="teaching_assistant",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=38,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=1200,
        expected_output_tokens=600,
    ),
    "summarization": FeatureProfile(
        feature_id="summarization",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=42,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=2000,
        expected_output_tokens=600,
    ),
    "academic_proofreading": FeatureProfile(
        feature_id="academic_proofreading",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=43,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=1500,
        expected_output_tokens=800,
    ),
    "writing_improvement": FeatureProfile(
        feature_id="writing_improvement",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=44,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=1500,
        expected_output_tokens=800,
    ),
    "outline_generation": FeatureProfile(
        feature_id="outline_generation",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=45,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=1000,
        expected_output_tokens=400,
    ),
    "plain_language_explanation": FeatureProfile(
        feature_id="plain_language_explanation",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=46,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=1000,
        expected_output_tokens=400,
    ),
    "research_brainstorming": FeatureProfile(
        feature_id="research_brainstorming",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=47,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=1000,
        expected_output_tokens=800,
    ),
    "academic_tone": FeatureProfile(
        feature_id="academic_tone",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=48,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=1200,
        expected_output_tokens=600,
    ),
    "teaching_simplification": FeatureProfile(
        feature_id="teaching_simplification",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=49,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=800,
        expected_output_tokens=500,
    ),
    "teaching_explanation": FeatureProfile(
        feature_id="teaching_explanation",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=50,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=800,
        expected_output_tokens=600,
    ),
    "admin_copilot": FeatureProfile(
        feature_id="admin_copilot",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=30,       # admin = elevated priority
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=True,
        typical_context_tokens=1000,
        expected_output_tokens=400,
    ),
    "general": FeatureProfile(
        feature_id="general",
        base_complexity=ComplexityLevel.MEDIUM,
        priority_score=60,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=1500,
        expected_output_tokens=800,
    ),
    # ── LOW ──────────────────────────────────────────────────────────────────
    "grammar_correction": FeatureProfile(
        feature_id="grammar_correction",
        base_complexity=ComplexityLevel.LOW,
        priority_score=55,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=True,
        typical_context_tokens=800,
        expected_output_tokens=500,
    ),
    "paraphrasing": FeatureProfile(
        feature_id="paraphrasing",
        base_complexity=ComplexityLevel.LOW,
        priority_score=56,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=800,
        expected_output_tokens=500,
    ),
    "translation": FeatureProfile(
        feature_id="translation",
        base_complexity=ComplexityLevel.LOW,
        priority_score=57,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=800,
        expected_output_tokens=600,
    ),
    "local_chat": FeatureProfile(
        feature_id="local_chat",
        base_complexity=ComplexityLevel.LOW,
        priority_score=58,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=1000,
        expected_output_tokens=400,
    ),
    "email_drafting": FeatureProfile(
        feature_id="email_drafting",
        base_complexity=ComplexityLevel.LOW,
        priority_score=62,
        cacheable=False,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=400,
        expected_output_tokens=200,
    ),
    "bullet_points": FeatureProfile(
        feature_id="bullet_points",
        base_complexity=ComplexityLevel.LOW,
        priority_score=65,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=600,
        expected_output_tokens=250,
    ),
    "title_generation": FeatureProfile(
        feature_id="title_generation",
        base_complexity=ComplexityLevel.LOW,
        priority_score=68,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=500,
        expected_output_tokens=60,
    ),
    "subtitle_generation": FeatureProfile(
        feature_id="subtitle_generation",
        base_complexity=ComplexityLevel.LOW,
        priority_score=69,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=True,
        allow_rule_downgrade=False,
        typical_context_tokens=300,
        expected_output_tokens=60,
    ),
    # ── VERY_LOW (Rule Engine native) ────────────────────────────────────────
    "keyword_extraction": FeatureProfile(
        feature_id="keyword_extraction",
        base_complexity=ComplexityLevel.VERY_LOW,
        priority_score=85,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=False,
        allow_rule_downgrade=False,
        typical_context_tokens=0,
        expected_output_tokens=0,
    ),
    "reference_validation": FeatureProfile(
        feature_id="reference_validation",
        base_complexity=ComplexityLevel.VERY_LOW,
        priority_score=82,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=False,
        allow_rule_downgrade=False,
        typical_context_tokens=0,
        expected_output_tokens=0,
    ),
    "profile_completion": FeatureProfile(
        feature_id="profile_completion",
        base_complexity=ComplexityLevel.VERY_LOW,
        priority_score=90,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=False,
        allow_rule_downgrade=False,
        typical_context_tokens=0,
        expected_output_tokens=0,
    ),
    "alert_generation": FeatureProfile(
        feature_id="alert_generation",
        base_complexity=ComplexityLevel.VERY_LOW,
        priority_score=80,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=False,
        allow_rule_downgrade=False,
        typical_context_tokens=0,
        expected_output_tokens=0,
    ),
    "citation_metrics": FeatureProfile(
        feature_id="citation_metrics",
        base_complexity=ComplexityLevel.VERY_LOW,
        priority_score=83,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=False,
        allow_rule_downgrade=False,
        typical_context_tokens=0,
        expected_output_tokens=0,
    ),
    "research_stats": FeatureProfile(
        feature_id="research_stats",
        base_complexity=ComplexityLevel.VERY_LOW,
        priority_score=86,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=False,
        allow_rule_downgrade=False,
        typical_context_tokens=0,
        expected_output_tokens=0,
    ),
    "profile_report": FeatureProfile(
        feature_id="profile_report",
        base_complexity=ComplexityLevel.VERY_LOW,
        priority_score=88,
        cacheable=True,
        min_subscription_tier="free",
        allow_local_downgrade=False,
        allow_rule_downgrade=False,
        typical_context_tokens=0,
        expected_output_tokens=0,
    ),
}

# Default profile for unknown features
_DEFAULT_PROFILE = FeatureProfile(
    feature_id="unknown",
    base_complexity=ComplexityLevel.MEDIUM,
    priority_score=60,
    cacheable=False,
    min_subscription_tier="free",
    allow_local_downgrade=True,
    allow_rule_downgrade=False,
    typical_context_tokens=1500,
    expected_output_tokens=800,
)


def get_profile(feature_id: str) -> FeatureProfile:
    return _PROFILES.get(feature_id, _DEFAULT_PROFILE)


def list_profiles() -> list[FeatureProfile]:
    return list(_PROFILES.values())


def get_all_feature_ids() -> list[str]:
    return list(_PROFILES.keys())
