"""
Agent Registry for the Autonomous Research Agent system.

Each entry describes one specialized agent: mission, capabilities, required inputs,
produced outputs, required permissions, cost estimate, and health status.

These are metadata entries — actual execution happens in orchestrator.py.
"""
from __future__ import annotations

from .models import SAFE_ACTIONS, IRREVERSIBLE_ACTIONS

_REGISTRY: list[dict] = [
    {
        "name":         "literature",
        "label":        "Literature Agent",
        "mission":      "Search, summarize, and synthesize academic literature from OpenAlex and platform knowledge graph",
        "capabilities": ["semantic search", "gap identification", "trend detection", "citation network"],
        "inputs":       ["research_topic", "date_range", "source_types"],
        "outputs":      ["literature_summary", "key_papers", "research_gaps", "trend_report"],
        "permissions":  ["literature_search"],
        "safe_actions": ["literature_search", "trend_monitoring"],
        "approval_required_actions": [],
        "cost_estimate_credits": 3,
        "estimated_duration_s": 45,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["OpenAlex API", "Synaptiq LKG", "CrossRef"],
    },
    {
        "name":         "writing",
        "label":        "Writing Agent",
        "mission":      "Analyze, improve, and draft academic text based on manuscript context",
        "capabilities": ["quality check", "structure improvement", "abstract generation", "section drafting"],
        "inputs":       ["manuscript_id", "section", "target_journal"],
        "outputs":      ["improvement_suggestions", "draft_text", "quality_score"],
        "permissions":  ["manuscript_read"],
        "safe_actions": ["document_quality_check", "draft_generation"],
        "approval_required_actions": [],
        "cost_estimate_credits": 4,
        "estimated_duration_s": 60,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq manuscripts DB"],
    },
    {
        "name":         "reviewer",
        "label":        "Reviewer Agent",
        "mission":      "Simulate peer review feedback based on manuscript content and target journal",
        "capabilities": ["review simulation", "critique generation", "revision suggestions"],
        "inputs":       ["manuscript_id", "target_journal"],
        "outputs":      ["review_report", "major_revisions", "minor_revisions"],
        "permissions":  ["manuscript_read"],
        "safe_actions": ["reviewer_simulation", "document_quality_check"],
        "approval_required_actions": [],
        "cost_estimate_credits": 5,
        "estimated_duration_s": 90,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq manuscripts DB"],
        "important_note": "SIMULATION ONLY — not a real peer reviewer. Always labeled as simulation.",
    },
    {
        "name":         "journal",
        "label":        "Journal Agent",
        "mission":      "Match manuscripts to appropriate journals based on topic, scope, and quality indicators",
        "capabilities": ["journal matching", "scope analysis", "submission requirements"],
        "inputs":       ["manuscript_id", "target_domains"],
        "outputs":      ["journal_recommendations", "match_scores", "submission_guides"],
        "permissions":  ["journal_search"],
        "safe_actions": ["journal_search", "recommendation_generation"],
        "approval_required_actions": [],
        "cost_estimate_credits": 2,
        "estimated_duration_s": 30,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq journals DB", "LKG"],
    },
    {
        "name":         "citation",
        "label":        "Citation Agent",
        "mission":      "Verify, format, and suggest citations using CrossRef and DOI validation",
        "capabilities": ["DOI validation", "citation formatting", "missing citation detection"],
        "inputs":       ["manuscript_id", "citation_style"],
        "outputs":      ["verified_citations", "missing_refs", "format_corrections"],
        "permissions":  ["citation_analysis"],
        "safe_actions": ["citation_analysis", "reference_formatting"],
        "approval_required_actions": [],
        "cost_estimate_credits": 2,
        "estimated_duration_s": 30,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["CrossRef API", "Synaptiq manuscripts DB"],
    },
    {
        "name":         "statistics",
        "label":        "Statistics Agent",
        "mission":      "Review statistical methods and suggest appropriate analyses",
        "capabilities": ["method review", "power analysis advice", "visualization suggestions"],
        "inputs":       ["manuscript_id", "study_type"],
        "outputs":      ["stats_report", "method_issues", "improvement_suggestions"],
        "permissions":  ["manuscript_read"],
        "safe_actions": ["statistical_analysis", "document_quality_check"],
        "approval_required_actions": [],
        "cost_estimate_credits": 3,
        "estimated_duration_s": 60,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq manuscripts DB"],
    },
    {
        "name":         "ethics",
        "label":        "Ethics Agent",
        "mission":      "Flag potential ethical concerns in research design and manuscript content",
        "capabilities": ["ethics flag detection", "IRB checklist", "consent verification"],
        "inputs":       ["manuscript_id"],
        "outputs":      ["ethics_flags", "recommendations", "checklist"],
        "permissions":  ["manuscript_read"],
        "safe_actions": ["document_quality_check"],
        "approval_required_actions": [],
        "cost_estimate_credits": 2,
        "estimated_duration_s": 30,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq manuscripts DB"],
        "important_note": "Flagging only — not a formal ethics approval process.",
    },
    {
        "name":         "funding",
        "label":        "Funding Agent",
        "mission":      "Search and match funding opportunities from platform grants database",
        "capabilities": ["grant search", "eligibility analysis", "deadline tracking"],
        "inputs":       ["research_topic", "career_stage", "country"],
        "outputs":      ["funding_opportunities", "match_scores", "deadline_alerts"],
        "permissions":  ["funding_search"],
        "safe_actions": ["funding_search", "recommendation_generation"],
        "approval_required_actions": [],
        "cost_estimate_credits": 2,
        "estimated_duration_s": 20,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq grants DB"],
    },
    {
        "name":         "grant_writer",
        "label":        "Grant Writer Agent",
        "mission":      "Draft grant application sections from research context and funding requirements",
        "capabilities": ["abstract drafting", "aims generation", "budget narrative"],
        "inputs":       ["funding_opportunity", "research_summary", "cv_summary"],
        "outputs":      ["draft_sections", "key_points", "checklist"],
        "permissions":  ["manuscript_read", "draft_generation"],
        "safe_actions": ["draft_generation"],
        "approval_required_actions": ["apply_for_grant"],
        "cost_estimate_credits": 8,
        "estimated_duration_s": 120,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq platform data", "Twin profile"],
        "important_note": "Drafts only. Grant submission always requires researcher approval.",
    },
    {
        "name":         "collaboration",
        "label":        "Collaboration Agent",
        "mission":      "Discover and suggest potential research collaborators from the knowledge graph",
        "capabilities": ["collaborator matching", "network analysis", "team composition"],
        "inputs":       ["research_topic", "project_id"],
        "outputs":      ["collaborator_suggestions", "match_reasons", "contact_draft"],
        "permissions":  ["collaboration_suggestions"],
        "safe_actions": ["collaboration_suggestions", "recommendation_generation"],
        "approval_required_actions": ["invite_collaborator", "send_email"],
        "cost_estimate_credits": 2,
        "estimated_duration_s": 20,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq LKG", "platform collaborations DB"],
    },
    {
        "name":         "teaching",
        "label":        "Teaching Agent",
        "mission":      "Analyze teaching activity and suggest curriculum improvements",
        "capabilities": ["lesson analysis", "curriculum suggestions", "student engagement"],
        "inputs":       ["user_id"],
        "outputs":      ["teaching_report", "suggestions"],
        "permissions":  ["teaching_analysis"],
        "safe_actions": ["teaching_analysis", "recommendation_generation"],
        "approval_required_actions": [],
        "cost_estimate_credits": 2,
        "estimated_duration_s": 30,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq teaching DB", "Twin profile"],
    },
    {
        "name":         "institution",
        "label":        "Institution Agent",
        "mission":      "Analyze institutional research performance from aggregated platform data",
        "capabilities": ["KPI computation", "benchmarking", "performance trends"],
        "inputs":       ["institution_name"],
        "outputs":      ["institution_report", "kpis", "benchmarks"],
        "permissions":  ["institution_read"],
        "safe_actions": ["recommendation_generation"],
        "approval_required_actions": ["edit_institution_record", "publish_report"],
        "cost_estimate_credits": 3,
        "estimated_duration_s": 45,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq platform data", "LKG"],
    },
    {
        "name":         "knowledge_graph",
        "label":        "Knowledge Graph Agent",
        "mission":      "Update and enrich the Living Knowledge Graph from new research activity",
        "capabilities": ["node creation", "edge inference", "topic enrichment"],
        "inputs":       ["entity_type", "entity_id"],
        "outputs":      ["graph_updates", "new_connections", "enrichment_report"],
        "permissions":  ["knowledge_graph_update"],
        "safe_actions": ["knowledge_graph_update"],
        "approval_required_actions": [],
        "cost_estimate_credits": 2,
        "estimated_duration_s": 20,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq LKG", "platform data"],
    },
    {
        "name":         "discovery",
        "label":        "Discovery Agent",
        "mission":      "Uncover hidden connections, emerging topics, and opportunities from graph reasoning",
        "capabilities": ["connection discovery", "trend detection", "opportunity identification"],
        "inputs":       ["user_id", "research_domain"],
        "outputs":      ["discoveries", "opportunities", "emerging_topics"],
        "permissions":  ["literature_search"],
        "safe_actions": ["literature_search", "trend_monitoring"],
        "approval_required_actions": [],
        "cost_estimate_credits": 3,
        "estimated_duration_s": 40,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq LKG", "OpenAlex"],
    },
    {
        "name":         "monitoring",
        "label":        "Monitoring Agent",
        "mission":      "Continuously watch publication feeds, citations, and grants for meaningful changes",
        "capabilities": ["publication monitoring", "citation tracking", "grant alerts", "trend alerts"],
        "inputs":       ["topics", "check_interval_hours"],
        "outputs":      ["alerts", "summaries", "change_reports"],
        "permissions":  ["trend_monitoring", "background_sync"],
        "safe_actions": ["trend_monitoring", "background_sync"],
        "approval_required_actions": [],
        "cost_estimate_credits": 1,
        "estimated_duration_s": 30,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["OpenAlex API", "Synaptiq grants DB", "CrossRef"],
        "background": True,
    },
    {
        "name":         "repository",
        "label":        "Repository Agent",
        "mission":      "Organize and tag repository items based on content analysis",
        "capabilities": ["auto-tagging", "duplicate detection", "organization suggestions"],
        "inputs":       ["user_id"],
        "outputs":      ["organization_report", "tag_suggestions", "duplicate_list"],
        "permissions":  ["repository_organization"],
        "safe_actions": ["repository_organization", "document_quality_check"],
        "approval_required_actions": ["delete_document"],
        "cost_estimate_credits": 2,
        "estimated_duration_s": 30,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq repository DB"],
    },
    {
        "name":         "submission",
        "label":        "Submission Agent",
        "mission":      "Prepare and check a manuscript for journal submission (checklist only — never submits)",
        "capabilities": ["formatting check", "requirement verification", "cover letter draft", "submission checklist"],
        "inputs":       ["manuscript_id", "target_journal"],
        "outputs":      ["submission_checklist", "cover_letter_draft", "missing_items"],
        "permissions":  ["manuscript_read", "draft_generation"],
        "safe_actions": ["document_quality_check", "draft_generation", "reference_formatting"],
        "approval_required_actions": ["submit_manuscript"],
        "cost_estimate_credits": 4,
        "estimated_duration_s": 60,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq manuscripts DB", "journal requirements"],
        "important_note": "This agent prepares for submission. The actual submission requires researcher approval.",
    },
    {
        "name":         "planner",
        "label":        "Planner Agent",
        "mission":      "Generate and optimize research workflow plans from mission descriptions",
        "capabilities": ["workflow generation", "dependency mapping", "resource estimation"],
        "inputs":       ["mission_description", "available_agents", "user_context"],
        "outputs":      ["workflow_plan", "step_sequence", "resource_estimate"],
        "permissions":  [],
        "safe_actions": ["recommendation_generation"],
        "approval_required_actions": [],
        "cost_estimate_credits": 1,
        "estimated_duration_s": 10,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Synaptiq platform data", "Twin profile"],
    },
    {
        "name":         "career",
        "label":        "Career Agent",
        "mission":      "Analyze career trajectory and suggest milestones based on Twin profile",
        "capabilities": ["promotion analysis", "milestone tracking", "gap identification"],
        "inputs":       ["user_id"],
        "outputs":      ["career_report", "milestones", "gap_analysis"],
        "permissions":  ["career_analysis"],
        "safe_actions": ["career_analysis", "recommendation_generation"],
        "approval_required_actions": [],
        "cost_estimate_credits": 3,
        "estimated_duration_s": 40,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Twin profile", "Synaptiq platform data"],
    },
    {
        "name":         "validation",
        "label":        "Validation Agent",
        "mission":      "Quality-check all mission outputs before delivery for evidence compliance and consistency",
        "capabilities": ["evidence verification", "consistency check", "integrity check", "completeness check"],
        "inputs":       ["mission_outputs", "mission_context"],
        "outputs":      ["validation_report", "issues_found", "confidence_assessment"],
        "permissions":  [],
        "safe_actions": ["document_quality_check"],
        "approval_required_actions": [],
        "cost_estimate_credits": 1,
        "estimated_duration_s": 15,
        "version":      "1.0",
        "health":       "active",
        "evidence_sources": ["Mission outputs"],
        "internal": True,  # runs automatically, not user-selectable
    },
]

_BY_NAME = {a["name"]: a for a in _REGISTRY}


def list_agents(include_internal: bool = False) -> list[dict]:
    return [a for a in _REGISTRY if include_internal or not a.get("internal")]


def get_agent(name: str) -> dict | None:
    return _BY_NAME.get(name)


def agents_for_mission_type(mission_type: str) -> list[str]:
    """Return recommended agent sequence for a mission type keyword."""
    templates = {
        "manuscript":    ["literature", "ethics", "statistics", "writing", "citation", "reviewer", "journal", "submission"],
        "literature":    ["literature", "discovery"],
        "funding":       ["funding", "grant_writer"],
        "monitor":       ["monitoring", "discovery"],
        "collaboration": ["collaboration", "knowledge_graph"],
        "review":        ["writing", "statistics", "ethics", "reviewer"],
        "career":        ["career", "knowledge_graph"],
        "teaching":      ["teaching"],
        "repository":    ["repository", "knowledge_graph"],
        "institution":   ["institution", "knowledge_graph"],
    }
    for keyword, agents in templates.items():
        if keyword in mission_type.lower():
            return agents
    return ["literature", "writing"]  # default
